import { TEMPLATES } from '../../src/content/templates'
import { AUTHORING_FORMAT, AUTHORING_VERSION, FIX_MAX_SHIFT, MAX_STEP_SIZE } from '../../src/core/authoring'
import { BASEPLATE_COLORS, PLATE_MAX } from '../../src/core/baseplate'
import { CELL, MAX_SCALE, WATER_TAG } from '../../src/core/city'
import { COLORS } from '../../src/core/colors'
import { DEFAULT_HAT_COLOR, FIG_ACCESSORIES, FIG_FACES, FIG_HATS, FIG_PRESETS, FIG_PRINTS } from '../../src/core/figures'
import { MAZE_MAX_SIZE, MAZE_MIN_SIZE } from '../../src/core/maze'
import { MAX_BRICKS, MAX_HEIGHT_PLATES } from '../../src/core/model'
import { PARTS, PART_CATEGORIES } from '../../src/core/parts/catalog'
import { SHARE_LIMITS } from '../../src/core/shareImport'
import type { PartDef } from '../../src/core/types'

/**
 * Reference docs generated from the real catalog (parts, colours, figures, templates, prints) and
 * the authoring rules, so the skill and the web prompt never drift from the game. Written by
 * `npm run bt:ref` (scripts/bt-gen-reference.ts).
 */

export const GENERATED_NOTE = '<!-- GENERATED by `npm run bt:ref` (scripts/bt-gen-reference.ts) from the game catalog. Do not edit by hand: re-run the script. -->'

const plates = (h: number) => (h % 3 === 0 ? `${h} (${h / 3} brick${h === 3 ? '' : 's'})` : `${h}`)

/** What a part looks like / which way it faces, from its shape. */
const SHAPE_NOTE: Partial<Record<PartDef['shape'], string>> = {
  box: '',
  tile: 'smooth top, no studs',
  slope: 'high side at the back (-z), slopes down to the front (+z) at r=0',
  slope_inv: 'upside-down slope: wide on top, narrow at the bottom; slopes under the front (+z) at r=0',
  cylinder: 'round',
  cone: 'round cone, pointed top, no studs',
  nose_cone: 'round nose cone (rocket tip), no studs',
  dish: 'radar dish / round plate, no studs',
  engine: 'jet / rocket engine nozzle, no studs',
  fin: 'thin fin, tall at the back (-z), sloping to the front',
  window: 'frame with glass; lies along x at r=0 (a wall along x); r=1 for a wall along z',
  door: 'door in a frame; along x at r=0; r=1 for a wall along z',
  fence: 'low fence along x at r=0',
  bars: 'jail bars in a frame, along x at r=0',
  wheel: 'tyre, axle along x: put wheels at the sides of a vehicle (they sit on the plate, y=0)',
  table: 'table, no studs',
  chair: 'chair: backrest at -z, faces +z at r=0',
  counter: 'kitchen counter, front +z',
  stove: 'stove / oven, front +z',
  fridge: 'fridge, front +z',
  sign: 'sign board on a post, panel facing +z',
  lamp: 'street lamp, 4 bricks tall',
  steering: 'steering wheel on a dashboard, faces +z',
  computer: 'computer with a printed screen, faces +z',
  bed: 'bed, pillow at -z',
  tree: 'pine tree, 4 bricks tall',
  bush: 'round bush',
  flower: 'flower',
  flag: 'flag: pole on the -x stud, flies toward +x',
  antenna: 'thin antenna / pole',
  tile_print: 'printed tile (picture drawn in its own colours; c is the tile edge)',
  minifig: 'minifigure; faces +z at r=0; its look comes from "fig", not "c"',
}

/** "Use this for..." hints by part id prefix or shape. */
function hintFor(p: PartDef): string {
  if (p.id.startsWith('brick_')) return p.w === 1 || p.d === 1 ? 'walls (1 stud thick), pillars, details' : 'solid blocks, thick walls, bases'
  if (p.id.startsWith('plate_')) return p.w * p.d >= 16 ? 'floors, foundations, roofs, vehicle chassis' : 'thin layers (1/3 brick), floors, ledges, steps'
  if (p.id.startsWith('tile_')) return 'smooth floors, paths, finishing tops'
  const byShape: Partial<Record<PartDef['shape'], string>> = {
    slope: 'roofs, ramps, car bonnets / windscreens',
    slope_inv: 'overhangs, under roof edges, boat hulls',
    cylinder: 'columns, towers, wheels hubs, barrels',
    cone: 'tower tips, traffic cones, roof finials',
    nose_cone: 'rocket and plane noses, round tower roofs',
    dish: 'satellite dishes, round lamps, wheels covers',
    engine: 'rocket / jet engines, exhausts',
    fin: 'rocket fins, plane tails, shark fins',
    window: p.h >= 9 ? 'big windows, shop fronts (3 bricks tall)' : 'small windows (2 bricks tall)',
    door: 'doors (6 bricks tall: walls need 6 courses around it)',
    fence: 'fences, railings, balconies',
    bars: 'jail windows, cages, gates',
    wheel: p.h >= 8 ? 'big wheels: trucks, fire engines' : 'small wheels: cars, carts',
    table: 'tables, desks', chair: 'chairs, seats', counter: 'kitchens, shop counters', stove: 'kitchens',
    fridge: 'kitchens', sign: 'shop signs, road signs', lamp: 'street lights', steering: 'vehicle cockpits',
    computer: 'offices, police stations', bed: 'bedrooms', tree: 'trees', bush: 'bushes, hedges', flower: 'gardens',
    flag: 'flags on roofs and towers', antenna: 'antennas, poles, masts', tile_print: 'signs and details (see prints)',
    minifig: 'people',
  }
  return byShape[p.shape] ?? ''
}

export function partsMd(): string {
  const lines = [
    GENERATED_NOTE,
    '# Parts',
    '',
    `Every part id the game knows (${PARTS.length}). Footprint \`w x d\` is in studs at r=0: w along x, d along z.`,
    'Odd rotations (r=1, r=3) swap it to `d x w`. Height is in plates: a plate is 1, a brick 3.',
    'Ids name sizes their own way (`slope_2x4` is 4 wide along x and 2 deep): trust the w x d column, not the id.',
    '',
  ]
  for (const cat of PART_CATEGORIES) {
    const parts = PARTS.filter((p) => p.category === cat)
    if (parts.length === 0) continue
    lines.push(`## ${cat}`, '', '| id | w x d | height (plates) | studs | notes | use for |', '|---|---|---|---|---|---|')
    for (const p of parts) {
      const note = [SHAPE_NOTE[p.shape] ?? '', p.print ? `print: \`${p.print}\`` : '', p.tags?.length ? `tags: ${p.tags.join(', ')}` : ''].filter(Boolean).join('; ')
      lines.push(`| \`${p.id}\` | ${p.w} x ${p.d} | ${plates(p.h)} | ${p.studs ? 'yes' : 'no'} | ${note} | ${hintFor(p)} |`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

/** Closest real LEGO colour names (BrickLink / LEGO), by colour id. */
const LEGO_NAMES: Record<number, string> = {
  0: 'White', 1: 'Black', 2: 'Red (Bright Red)', 3: 'Blue (Bright Blue)', 4: 'Yellow (Bright Yellow)',
  5: 'Green (Dark Green)', 6: 'Orange (Bright Orange)', 7: 'Light Bluish Gray / Light Gray (the usual modern grey)',
  8: 'Dark Bluish Gray / Dark Gray', 9: 'Reddish Brown / Brown', 10: 'Tan (Brick Yellow)', 11: 'Lime (Bright Yellowish Green)',
  12: 'Bright Pink / Light Pink', 13: 'Magenta / Purple', 14: 'Medium Azure / Dark Turquoise', 15: 'Trans-Clear (windows)',
  16: 'Trans-Red (lights)', 17: 'Trans-Dark Blue (siren)', 18: 'Trans-Yellow', 19: 'Trans-Green', 20: 'Trans-Orange',
  21: 'Dark Blue (Earth Blue)', 22: 'Dark Red', 23: 'Medium Blue', 24: 'Very light grey (lighter than LBG; default baseplate grey)',
  25: 'Dark Tan (Sand Yellow)', 26: 'Sand Green', 27: 'Lavender', 28: 'Flat Silver / Pearl Light Gray', 29: 'Pearl Gold',
}

export function colorsMd(): string {
  const lines = [
    GENERATED_NOTE,
    '# Colours',
    '',
    `Bricks use colour ids (\`c\`), never names. ${COLORS.length} colours, ids 0..${COLORS.length - 1}.`,
    'Trans colours render see-through (glass, lights); metal ones shiny. Figures cannot wear trans colours.',
    `Baseplate colours offered in the game: ${BASEPLATE_COLORS.join(', ')} (any id is accepted).`,
    '',
    '| id | name (en) | tên (vi) | hex | material | closest real LEGO colour |',
    '|---|---|---|---|---|---|',
    ...COLORS.map((c) => `| ${c.id} | ${c.name.en} | ${c.name.vi} | \`${c.hex}\` | ${c.trans ? 'trans' : c.metal ? 'metal' : 'solid'} | ${LEGO_NAMES[c.id] ?? '-'} |`),
    '',
    'Matching a photo: lighting shifts colours. Judge by the brightest clean face, then pick the nearest hex;',
    'prefer the common LEGO colours (white, black, red, blue, yellow, green, light/dark grey, tan, brown, orange).',
    '',
  ]
  return lines.join('\n')
}

export function figuresMd(): string {
  const style = (s: object) => `\`${JSON.stringify(s)}\``
  return [
    GENERATED_NOTE,
    '# Minifigures',
    '',
    'Part `minifig`: footprint 2 x 1 studs (w along x), 12 plates (4 bricks) tall, faces +z at r=0.',
    'In authoring JSON give `"fig"` as a preset id (`"fig": "chef"`) or a style object. `c` is ignored: a figure\'s',
    'colour is its torso colour. Put figures where the photo shows people, standing on the plate or on a floor.',
    '',
    '## Style fields',
    '',
    '| field | required | values |',
    '|---|---|---|',
    '| `torso` | yes | colour id (solid or metal) |',
    '| `legs` | yes | colour id |',
    '| `arms` | no | colour id; default = torso |',
    `| \`face\` | yes | ${FIG_FACES.map((f) => `\`${f}\``).join(', ')} |`,
    `| \`hat\` | yes | ${FIG_HATS.map((f) => `\`${f}\``).join(', ')} (hair counts as a hat) |`,
    `| \`hatColor\` | no | colour id; default per hat: ${Object.entries(DEFAULT_HAT_COLOR).map(([h, c]) => `${h} ${c}`).join(', ')} |`,
    `| \`print\` | yes | ${FIG_PRINTS.map((f) => `\`${f}\``).join(', ')} (torso picture) |`,
    `| \`accessory\` | no | ${FIG_ACCESSORIES.map((f) => `\`${f}\``).join(', ')} (in the right hand) |`,
    '',
    'No other fields are allowed.',
    '',
    '## Presets',
    '',
    '| preset | en | vi | style |',
    '|---|---|---|---|',
    ...FIG_PRESETS.map((p) => `| \`${p.id}\` | ${p.name.en} | ${p.name.vi} | ${style(p.style)} |`),
    '',
  ].join('\n')
}

const cells = (n: number) => Math.ceil(n / CELL)

export function templatesMd(): string {
  return [
    GENERATED_NOTE,
    '# Built-in templates',
    '',
    'Ready-made models a city can place without defining a blueprint: `"source": "tpl:<id>"`.',
    `Cells = footprint in city cells at s=1, rot=0 (a cell is ${CELL} studs; x s for a scaled placement, swapped for odd rot).`,
    `Templates tagged \`${WATER_TAG}\` must sit on (or across) water; all others on dry land.`,
    '',
    '| id | name (en) | tên (vi) | kind | baseplate | cells | bricks | tags |',
    '|---|---|---|---|---|---|---|---|',
    ...[...TEMPLATES].sort((a, b) => a.id.localeCompare(b.id)).map((t) =>
      `| \`tpl:${t.id}\` | ${t.name.en} | ${t.name.vi} | ${t.kind} | ${t.baseplate.w} x ${t.baseplate.d} | ${cells(t.baseplate.w)} x ${cells(t.baseplate.d)} | ${t.bricks.length} | ${t.tags.join(', ')} |`),
    '',
  ].join('\n')
}

/** What each printed tile shows. */
const PRINT_DESC: Record<string, string> = {
  police: 'navy police shield with a gold star and POLICE',
  fire: 'red fire-brigade badge with a flame and FIRE',
  clock: 'clock face (ten past ten)',
  stop: 'red octagonal STOP sign',
  arrow: 'blue road sign, white arrow pointing +x',
  menu: 'chalkboard restaurant menu',
  screen: 'computer screen: window, bar chart, text',
  robot_eyes: 'dark visor with two glowing eyes',
  number_112: 'emergency number 112 on a white plate with a red border',
  heart: 'red heart',
  star: 'yellow star',
}

export function printsMd(): string {
  const printed = PARTS.filter((p) => p.print)
  return [
    GENERATED_NOTE,
    '# Printed parts',
    '',
    'Flat 1-plate tiles (and the computer) with a picture in fixed colours. Prints read along +x at r=0.',
    'Use them for signs, faces of robots, clocks on towers, badges on police / fire buildings and vehicles.',
    '',
    '| part id | w x d | print | shows |',
    '|---|---|---|---|',
    ...printed.map((p) => `| \`${p.id}\` | ${p.w} x ${p.d} | \`${p.print}\` | ${PRINT_DESC[p.print!] ?? p.print} |`),
    '',
  ].join('\n')
}

// ---------------------------------------------------------------------------------------------
// shared prose: coordinates, schema, rules

export function coordinatesMd(level = '##'): string {
  return [
    `${level} Coordinates`,
    '',
    '- 1 stud = 1 unit along x and z. Heights count **plates**: `y` is the plate level of the brick\'s bottom (0 = on the baseplate). A plate or tile is 1 plate tall, a brick 3, so bricks stack at y = 0, 3, 6, 9...',
    '- Real proportions: a brick is 1 stud wide and 1.2 studs tall; a plate is 1/3 of a brick.',
    '- `x`, `z` = the **min corner**: the smallest x and z the part covers (integers >= 0).',
    '- Footprint: a part is `w x d` at r=0 (w along x, d along z). `r` = quarter turns counter-clockwise seen from above (0..3); r=1 or 3 swaps it to `d x w`. The part covers x..x+fx-1, z..z+fz-1, y..y+h-1.',
    '- Facing: parts with a front (slopes, windows, doors, figures, chairs...) face **+z at r=0**, +x at r=1, -z at r=2, -x at r=3. A slope\'s low edge is its front.',
    '- Photo mapping: **front = +z** (the side facing the camera), **x grows to the right**, y up; z=0 is the back row. The game\'s camera looks from the front-right.',
    `- Baseplate \`{w, d, c}\`: studs, 1..${PLATE_MAX}; use multiples of 8 (8, 16, 24, 32, 40, 48), leaving a stud or two of margin. \`c\` = colour id (defaults: building 5 green, vehicle 8 dark grey, prop 10 tan).`,
    `- City: a cell is ${CELL} studs. Placements give the min-corner cell \`cx, cz\`, \`rot\` 0..3 and size \`s\` 1..${MAX_SCALE}; a model covers ceil(w*s/${CELL}) x ceil(d*s/${CELL}) cells (swapped for odd rot). Roads, rails and terrain are lists of \`"cx,cz"\` keys.`,
    '',
  ].join('\n')
}

export function rulesMd(level = '##'): string {
  return [
    `${level} Build rules (checked; the import refuses a model that breaks them)`,
    '',
    '- Every part id and colour id must exist (see the tables).',
    '- Inside the baseplate: 0 <= x and x + fx <= w, 0 <= z and z + fz <= d.',
    `- Height: y >= 0 and y + h <= ${MAX_HEIGHT_PLATES} plates.`,
    '- **No overlaps**: no two parts share a stud cell at the same plate level.',
    '- **Support**: each part sits on the baseplate (y = 0) or has at least one footprint cell directly on top of another part (that part ends exactly at plate y). Nothing floats; nothing hangs under another part.',
    `- At most ${MAX_BRICKS} parts per model; a city has at most ${SHARE_LIMITS.cityBlueprints} blueprints, size <= ${SHARE_LIMITS.citySize}; names <= ${SHARE_LIMITS.nameLength} characters.`,
    `- Build steps (\`withSteps\`): built automatically layer by layer, <= ${MAX_STEP_SIZE} parts per step; each part must fit using only parts of earlier steps.`,
    '- City: a placement must stay inside the city and not cover a road, a rail, another placement or water (models tagged `water` instead need some water under them). No water under roads or rails; a road and a rail may share a cell only as a level crossing of two perpendicular straights.',
    '',
  ].join('\n')
}

export function approximationMd(level = '##'): string {
  return [
    `${level} Approximation rules`,
    '',
    '- Keep the **silhouette, proportions and colour blocks**; drop fine detail. Count studs on visible tops to get sizes.',
    '- Use the **biggest bricks that fit** (2x4, 2x6, 1x6, plates 4x8): fewer parts, sturdier, easier to build.',
    '- Make walls 1 stud thick and keep interiors **hollow**; stagger joints between courses when you can.',
    '- Map special pieces to the closest catalog part (an arch -> bricks + a window or door; a curved slope -> slope; a round brick -> round_1x1/2x2; a transparent piece -> a trans colour).',
    '- Windows: window_1x2x2 (2 bricks tall) or window_1x4x3 (3 bricks tall); doors are 6 bricks tall.',
    '- Roofs: slopes facing outwards (front row r=0, back row r=2, sides r=1 / r=3), a brick or plate ridge between them.',
    '- Vehicles (`blueprintKind` vehicle) drive toward **-z**: put the nose at the small-z end. Wheels stand on the plate (y=0) under the sides; the chassis plate rests on them (y=5 on wheel_small, y=8 on wheel_large).',
    '- Put minifigures where people are. Build bottom-up and check each layer has support.',
    '',
  ].join('\n')
}

export const EXAMPLE = {
  format: AUTHORING_FORMAT,
  version: AUTHORING_VERSION,
  kind: 'model',
  name: 'Tháp nhỏ',
  blueprintKind: 'building',
  baseplate: { w: 8, d: 8, c: 5 },
  withSteps: true,
  bricks: [
    { p: 'brick_2x4', x: 2, y: 0, z: 2, r: 0, c: 2 },
    { p: 'brick_2x4', x: 2, y: 3, z: 2, r: 0, c: 4 },
    { p: 'brick_2x2', x: 2, y: 6, z: 2, r: 0, c: 3 },
    { p: 'slope_2x2', x: 2, y: 6, z: 4, r: 0, c: 0 },
  ],
}

/** The example as compact JSON: one brick per line. */
export function exampleJson(): string {
  const { bricks, ...head } = EXAMPLE
  const top = Object.entries(head).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  return `{\n${top.join('\n')}\n  "bricks": [\n${bricks.map((b) => `    ${JSON.stringify(b)}`).join(',\n')}\n  ]\n}`
}

export function schemaMd(level = '##'): string {
  return [
    `${level} Authoring JSON`,
    '',
    `Every file starts with \`"format": "${AUTHORING_FORMAT}", "version": ${AUTHORING_VERSION}\` (the game recognises plain JSON by it) and a \`kind\`.`,
    '',
    '**Model** (`"kind": "model"`):',
    '',
    '| field | type | notes |',
    '|---|---|---|',
    '| `name` | string | <= 40 characters |',
    '| `blueprintKind` | `"building"` \\| `"vehicle"` \\| `"prop"` | default building |',
    '| `baseplate` | `{ "w", "d", "c"? }` | studs; c = colour id |',
    '| `bricks` | list | `{ "p", "x", "y", "z", "r"?, "c", "fig"? }`; p = part id, r default 0, c = colour id (not for minifig), fig = preset id or style (minifig only); `note` is allowed and ignored |',
    `| \`withSteps\` | boolean | true = add step-by-step build instructions (Guided mode) |`,
    `| \`stepSize\` | 1..${MAX_STEP_SIZE} | parts per automatic step, default 4 |`,
    '| `steps` | list of lists | optional explicit steps: indices into `bricks` |',
    '| `tags` | list | optional, lower-case words |',
    '',
    '**City** (`"kind": "city"`): `name`, `size` (cells per side), `roads`, `rails` (lists of `"cx,cz"`), `terrain` `{ "water": [], "pavement": [], "sand": [] }` (grass elsewhere),',
    '`blueprints` (models as above plus a unique `"id"`, without `withSteps`), `placements` `[{ "source": "<blueprint id>" | "tpl:<template id>", "cx", "cz", "rot"?, "s"? }]`.',
    '',
    `**Maze** (\`"kind": "maze"\`): \`name\`, \`grid\` = list of equal rows (odd sizes ${MAZE_MIN_SIZE}..${MAZE_MAX_SIZE}): \`#\` wall, \`.\` floor, \`o\` coin, \`E\` entry, \`X\` exit (both on the outer wall ring, not corners); \`wallColor\`, \`floorColor\` optional colour ids.`,
    '',
    'Example (4 parts):',
    '',
    '```json',
    exampleJson(),
    '```',
    '',
  ].join('\n')
}

export function authoringMd(): string {
  return [
    GENERATED_NOTE,
    '# Authoring format',
    '',
    'What you write for `npm run bt:pack` (or paste into the game\'s 📥 import).',
    '',
    coordinatesMd(),
    schemaMd(),
    rulesMd(),
    approximationMd(),
    '## Repairs',
    '',
    `\`--fix\` (and the in-game import) drops exact duplicates and parts that overlap another at their own level, lifts a part sunk into the part below onto the nearest free support, and lowers / lifts a floating part onto the nearest support within ${FIX_MAX_SHIFT} plates when there is exactly one nearest choice. Every change is reported.`,
    '',
  ].join('\n')
}

// ---------------------------------------------------------------------------------------------
// the self-contained web prompt

function compactParts(): string {
  const rows = PARTS.map((p) => {
    const note = [SHAPE_NOTE[p.shape], hintFor(p)].filter(Boolean).join('; ')
    return `${p.id}|${p.w}x${p.d}|${p.h}|${p.category}${note ? `|${note}` : ''}`
  })
  return ['id|w x d|h(plates)|category|notes', ...rows].join('\n')
}

function compactColors(): string {
  return ['id|name|hex|LEGO name', ...COLORS.map((c) => `${c.id}|${c.name.en}${c.trans ? ' (trans)' : c.metal ? ' (metal)' : ''}|${c.hex}|${LEGO_NAMES[c.id] ?? ''}`)].join('\n')
}

export function promptMd(): string {
  const presets = FIG_PRESETS.map((p) => `${p.id} (${p.name.en})`).join(', ')
  const templates = [...TEMPLATES].sort((a, b) => a.id.localeCompare(b.id))
    .map((t) => `tpl:${t.id} ${t.kind} ${t.baseplate.w}x${t.baseplate.d} (${cells(t.baseplate.w)}x${cells(t.baseplate.d)} cells)${t.tags.includes(WATER_TAG) ? ' water' : ''}`).join('\n')
  return [
    GENERATED_NOTE,
    '',
    '> **Cách dùng (cho bố mẹ):** Mở ChatGPT, Claude.ai hoặc Gemini. Dán toàn bộ nội dung dưới đường kẻ vào ô chat, đính kèm ảnh chụp mô hình LEGO và gửi.',
    '> Bot sẽ trả lời bằng một khối ```json. Sao chép khối đó (hoặc lưu thành file `.json`). Trong BrickTown bấm **📥 Nhập**, rồi dán vào ô "Dán link vào đây" và bấm ✓, hoặc bấm "Chọn file" và chọn file `.json`. Game tự kiểm tra, tự sửa lỗi nhỏ và cho xem trước rồi mới thêm. Nếu game báo lỗi, gửi lại dòng lỗi cho bot để nó sửa.',
    '> Muốn có hướng dẫn lắp từng bước thì nhắn thêm "có hướng dẫn lắp". Muốn cả thành phố thì nói "làm thành phố".',
    '',
    '---',
    '',
    '# Task: turn the attached photo into a BrickTown model',
    '',
    'You convert a photo (or screenshot) of a LEGO / Duplo / brick build into **authoring JSON** for BrickTown, a LEGO-style building game for kids.',
    'Make a Workshop **model** by default; make a **city** when the photo shows a whole town or street layout, and add build steps (`"withSteps": true`) when asked for instructions.',
    'You only have this prompt and the photo: use only the part ids and colour ids listed below.',
    '',
    coordinatesMd(),
    schemaMd(),
    rulesMd(),
    approximationMd(),
    '## Workflow',
    '',
    '1. Name the objects in the photo; pick the main one (or the city layout).',
    '2. Measure in studs: count studs on visible tops; a brick is 1 stud wide and 1.2 studs tall, a plate 1/3 of a brick. Note width (x), depth (z), height (courses).',
    '3. Choose the baseplate (multiple of 8, a little bigger than the model) and centre the model on it.',
    '4. Build bottom-up, one course at a time (y = 0, 3, 6... for bricks; +1 per plate), walls first, then roof and details.',
    '5. Pick colour ids from the table by matching the photo\'s colours.',
    '',
    '## Parts (w x d at r=0, h in plates)',
    '',
    '```',
    compactParts(),
    '```',
    '',
    '## Colours',
    '',
    '```',
    compactColors(),
    '```',
    '',
    '## Minifigures',
    '',
    `Part \`minifig\` (2x1, 12 plates, faces +z). \`"fig"\`: a preset id - ${presets} - or a style object`,
    `\`{ "torso": colour, "legs": colour, "arms"?: colour, "face": ${FIG_FACES.join('|')}, "hat": ${FIG_HATS.join('|')}, "hatColor"?: colour, "print": ${FIG_PRINTS.join('|')}, "accessory"?: ${FIG_ACCESSORIES.join('|')} }\` (no trans colours).`,
    '',
    '## Templates for cities (`"source": "tpl:<id>"`)',
    '',
    '```',
    templates,
    '```',
    '',
    '## Self-check before answering (do it, silently)',
    '',
    '- Count the studs again: does the footprint (w x d, after rotation) match the photo? Is the height in plates (3 per brick)?',
    '- Go layer by layer from y=0: every part above 0 has a part ending exactly at its y under at least one of its studs; no two parts overlap.',
    '- Every part stays inside the baseplate, every `p` is in the parts table, every `c` is a number from the colours table, `r` is 0..3.',
    '- Placements in a city do not cover roads, rails, water or each other; template ids exist.',
    '- The JSON parses (no comments, no trailing commas) and has `"format"`, `"version"`, `"kind"`.',
    '',
    '## Output contract',
    '',
    'Reply with **exactly one** ```json code block containing the authoring JSON (one brick per line is fine), then a summary of **3 lines**:',
    'what it is and its size in studs; how many parts and the main colours; what you simplified or guessed.',
    'Nothing else: no extra code blocks, no explanations before the JSON.',
    '',
  ].join('\n')
}
